# Generated by Django 3.0.5 on 2020-04-26 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', mdeditor.fields.MDTextField()),
                ('update_time', models.DateTimeField()),
                ('solved_state', models.CharField(choices=[('T', 'solved'), ('F', 'unsolved')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RepoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mdeditor.fields.MDTextField()),
                ('update_time', models.DateTimeField()),
                ('belong_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gitlight.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_input_text', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField()),
                ('profile_picture', models.FileField(blank=True, upload_to='')),
                ('profile_user_id', models.IntegerField()),
                ('content_type', models.CharField(max_length=50)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='belong_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gitlight.RepoModel'),
        ),
    ]
